Add files ====================== The 100-matrix_mul module ======================
Using matrix_mul
-------------------

This is a text file to test the 100-matrix_mul module.  First import
100-matrix_mul from the matrix_mul module:

>>> matrix_mul = __import__('100-matrix_mul').matrix_mul

Now use it with:

>>> print(matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]]))
[[7, 10], [15, 22]]

>>> print(matrix_mul([[1, 2]], [[3, 4], [5, 6]]))
[[13, 16]]

>>> print(matrix_mul([], []))
Traceback (most recent call last):
ValueError: m_a can't be empty

>>> print(matrix_mul([[]], []))
Traceback (most recent call last):
ValueError: m_a can't be empty

>>> print(matrix_mul([[1, 2]], []))
Traceback (most recent call last):
ValueError: m_b can't be empty

>>> print(matrix_mul(3, [[1, 2]]))
Traceback (most recent call last):
TypeError: m_a must be a list

>>> print(matrix_mul([[1, 2]], 'x'))
Traceback (most recent call last):
TypeError: m_b must be a list

>>> print(matrix_mul([2, 4], [[1, 2]]))
Traceback (most recent call last):
TypeError: m_a must be a list of lists

>>> print(matrix_mul([[1, 2]], [2, 4]))
Traceback (most recent call last):
TypeError: m_b must be a list of lists

>>> print(matrix_mul())
Traceback (most recent call last):
TypeError: matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'

>>> print(matrix_mul([[1, 3]],[[1, 'a']]))
Traceback (most recent call last):
TypeError: m_b should contain only integers or floats

>>> print(matrix_mul([[1, 'a']], [[1, 3]]))
Traceback (most recent call last):
TypeError: m_a should contain only integers or floats

>>> print(matrix_mul([[1, 1]], [[1, 3]]))
Traceback (most recent call last):
ValueError: m_a and m_b can't be multiplied

>>> print(matrix_mul([[1, 1]], [[1, 3], [1, 3, 4]]))
Traceback (most recent call last):
TypeError: each row of m_b must be of the same size

>>> print(matrix_mul([[1, 3